Xandar/Xandar/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from Xandar import settings
from django.contrib.auth import views as auth_views
from accounts import views
from products.views import ProductListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('', include('core.urls')),
    path('product/', include('products.urls')),
    path('operations/', include('operations.urls')),
    path('product_list/', ProductListView.as_view(), name="product_list"),
    path('orders/', include('orders.urls')),



    

























    path('forgot_password/', views.check_email, name="check_email"),


    path('password-reset', 
    	auth_views.PasswordResetView.as_view(
            template_name='accounts/password_reset.html', html_email_template_name="accounts/email_reset_template.html",
            email_template_name='accounts/password_reset_email.html', subject_template_name="accounts/password_reset_subject.txt",
            ),
    		 name="password_reset"),

    path('password-reset/done', 
    	auth_views.PasswordResetDoneView.as_view(
    		template_name='accounts/password_reset_done.html'),
    		 name="password_reset_done"),

    path('password-reset-complete/', 
    	auth_views.PasswordResetCompleteView.as_view(
    		template_name='accounts/password_reset_complete.html'),
    		 name="password_reset_complete"),

    path('password-reset-confirm/<uidb64>/<token>/', 
    	auth_views.PasswordResetConfirmView.as_view(
    		template_name='accounts/password_reset_confirm.html'),
    		 name="password_reset_confirm"),


]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Xandar/accounts/urls.py
from django.urls import path, re_path
from . import views
app_name = 'accounts'
urlpatterns = [
    path('login/', views.login_page, name='login_app'),
    path('logout/', views.logout_user, name='logout_app'),
    path('reset_password/', views.reset_password, name="reset_password"),
    path('register/', views.user_register, name='registration'),
    path('dashboard/', views.dashboard, name='dashboard'),
    re_path('[A-Za-z0-9]*', views.login_page, name='login_app'),

]

Xandar/core/urls.py
from django.urls import path
from core import views
urlpatterns = [
    path('', views.index, name="index"),

]

Xandar/operations/urls.py
from django.urls import path
from . import views

app_name = 'operations'

urlpatterns = [
    path('wishlist/add/<int:pk>/', views.add_wishlist_item, name='add_wishlist_items'),
    path('wishlist/', views.list_wishlist_items, name='wishlist'),
    path('delete-item/<int:pk>/', views.delete_wishlist_items, name='delete_wishlist_items'),
    path('orders/', views.show_orders, name='orders'),
    path('address/', views.show_address, name='address'),
    path('track/', views.track_order, name='track'),
    path('cart/add/<int:product_id>/', views.add_to_cart, name='add_cart'),
    path('cart/', views.get_cart, name='view_cart'),
    path('cart/update/<int:product_id>/', views.update_cart, name='update_cart'),
    path('cart/delete/<int:product_id>/', views.delete_cart, name='delete_cart'),
]

Xandar/orders/urls.py
from django.urls import path
from .views import show_ordered_items,apply_coupon, place_order, get_delivery_addresses
app_name='orders'
urlpatterns = [
    path('', show_ordered_items, name='checkout'),
    path('apply/', apply_coupon, name='apply_name'),
    path('place_order/',place_order, name='place_order'),
    path('address/',get_delivery_addresses.as_view(), name='delivery_address'),
]

Xandar/products/urls.py
from django.urls import path
from . import views
app_name = 'products'
urlpatterns = [
    path('<int:pk>', views.ProductDetailView.as_view(), name='product_detail'),
    path('add/<int:pk>', views.product_add_wishlist_cart, name='product_add'),
]

Xandar/orders/models.py
from django.db import models

# Create your models here.

Xandar/operations/forms.py
from django import forms
choices = [(i, str(i)) for i in range(1, 4)]


class UpdateCartForm(forms.Form):
    quantity = forms.ChoiceField(choices=choices)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

Xandar/operations/views.py
from decimal import Decimal

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, DeleteView

from Xandar import settings
from core.models import Product, ProductImage, Cart, Items
from core.models import Customer, Wishlist
# Create your views here.
from operations.forms import UpdateCartForm


@login_required
def list_wishlist_items(request):
    try:
        user = Customer.objects.get(email=request.user.email)
        items = Wishlist.objects.filter(customer=request.user)
        if not len(items) == 0:
            context = {'items': items}
        else:
            context = {'no_item_found': True}
    except Customer.DoesNotExist:
        return redirect('accounts:login_app')
    return render(request, 'operations/wishlist.html', context)


def add_wishlist_item(request, pk):
    if request.user.is_authenticated:
        product = Product.objects.get(id=pk)
        try:
            Wishlist.objects.get(product=product)
            return 'Item Already Exists in your Wishlist'
        except Wishlist.DoesNotExist:
            image = ProductImage.objects.filter(product=product).first()
            Wishlist.objects.create(customer=request.user, product=product, product_image=image)
            print('been here')
            return 'Item Added To Wishlist successfully'
    else:
        return 'Login To Save This to your Wishlist'





@login_required
def delete_wishlist_items(request, pk):
    try:
        user = Customer.objects.get(email=request.user.email)
        items = Wishlist.objects.filter(customer=request.user)
        context = {'items': items}
        # import pdb; pdb.set_trace()
        if not len(items) == 0:
            if request.method == 'POST':
                Wishlist.objects.filter(id=pk).delete()
                context = {'items': items}
        else:
            context = {'no_item_found': True}
        return HttpResponse(list_wishlist_items(request))
    except Customer.DoesNotExist:
        return redirect('accounts:login_app')


def show_orders(request):
    return render(request, 'operations/orders.html')


def show_address(request):
    return render(request, 'operations/address.html')


def track_order(request):
    return render(request, 'operations/track.html')


def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


def add_to_cart(request, product_id, quantity=1):
    errors = ""
    print('inside')
    try:
        product = Product.objects.get(id=product_id)
    except Product.DoesNotExist:
        messages.error(request, "You are trying to add product that does not exist")
        return render(
            request, 'operations/cart.html')

    product_image = product.productimage_set.all()[0]

    if request.user.is_authenticated:

        try:
            cart = Cart.objects.get(user=request.user, is_ordered=False)
        except Cart.DoesNotExist:
            cart = Cart.objects.create(user=request.user)

        try:
            obj = Items.objects.get(cart=cart, product=product)
            if obj:
                return "You are adding the item that already exist"
        except:
            if quantity <= product.quantity :
                if quantity <= 3:
                    Items.objects.create(cart=cart, product=product, product_img=product_image, quantity=quantity,
                                     unit_price=product.price)
                else:
                    return "This item cannot be added more than 3"
                # return something
            else:
                return 'This item is not available that much you want to avail Sorry !!!!'
                # return render(
                #     request, 'operations/cart.html')

    else:

        ip_address = get_client_ip(request)

        request.session[settings.CART_SESSION_ID] = request.session.get(settings.CART_SESSION_ID, {})

        product_id = str(product_id)

        if request.session[settings.CART_SESSION_ID] is None:
            request.session[settings.CART_SESSION_ID] = {}
            request.session[settings.CART_SESSION_ID][product_id] = {
                'product': {'id': product_id, 'name': product.name},
                'quantity': 0, 'unit_price': product.price,
                'product_img': {'image': {'url': product_image.image.url}}
            }

        elif product_id not in request.session[settings.CART_SESSION_ID]:
            request.session[settings.CART_SESSION_ID][product_id] = {
                'product': {'id': product_id, 'name': product.name},
                'quantity': 0, 'unit_price': product.price,
                'product_img': {'image': {'url': product_image.image.url}}
            }
        else :
            return "You are adding the item that already exist"

        if quantity <= product.quantity :

            if quantity <=3:
                request.session[settings.CART_SESSION_ID][product_id]['quantity'] = quantity
                request.session.modified = True
            else:
                return "This item cannot be added more than 3 in cart"
        else:
            return 'This item is not available that much you want to avail Sorry !!!!'
    return 'Item added to Cart Successfully'


def get_cart(request):
    errors = ""
    form = UpdateCartForm()
    if request.user.is_authenticated:

        '''Code to add the anonymous cart items to the logged in user'''
        # request.session[settings.CART_SESSION_ID] = request.session.get(settings.CART_SESSION_ID, None)
        # if request.session[settings.CART_SESSION_ID]:
        #     try:
        #         cart = Cart.objects.filter(user=request.user, is_ordered=False)[0]
        #     except Cart.DoesNotExist:
        #         cart = Cart.objects.create(user=request.user)
        #
        #     for item in request.session[settings.CART_SESSION_ID].values():
        #         product = Product.objects.get(id=int(item['product']['id']))
        #         product_image = product.productimage_set.all()[0]
        #         Items.objects.create(cart=cart, product=product,
        #                              product_img=product.productimage_set.all()[0], quantity=item['quantity'],
        #                              unit_price=product.price)
        #     request.session[settings.CART_SESSION_ID] = {}
        #     request.session.modified = True

        try:
            cart = Cart.objects.get(user=request.user, is_ordered=False)
            print('run')
        except Cart.DoesNotExist:
            messages.error(request, "You don't have anything in cart")
            return render(request, 'operations/cart.html', {'errors': errors})

        items = Items.objects.filter(cart=cart)
        if len(items) == 0:
            errors = "You don't have anything in cart"
        total_price = sum(Decimal(item.unit_price) * item.quantity for item in items)

    else:
        items = []
        request.session[settings.CART_SESSION_ID] = request.session.get(settings.CART_SESSION_ID, None)
        if not request.session[settings.CART_SESSION_ID]:
            errors = "You don't have anything in cart"
            return render(
                request, 'operations/cart.html', {'errors': errors})

        for item in request.session[settings.CART_SESSION_ID].values():
            # item['price'] = Decimal(item['price'])
            item['total_price'] = item['unit_price'] * item['quantity']
            items.append(item)

        total_price = sum(Decimal(item['unit_price']) * item['quantity'] for item in
                          request.session[settings.CART_SESSION_ID].values())
    return render(request, 'operations/cart.html',
                  {'items': items, 'total_price': total_price, 'form': form, 'errors': errors})


def update_cart(request, product_id):
    errors = " "
    form = UpdateCartForm()
    if request.method == "POST":
        form = UpdateCartForm(request.POST)
        if form.is_valid():
            try:
                product = Product.objects.get(id=product_id)
            except Product.DoesNotExist:
                messages.error(request, "You are updating product that does not exist !!!")

            if request.user.is_authenticated:
                try:
                    cart = Cart.objects.get(user=request.user, is_ordered=False)
                except Cart.DoesNotExist:
                    messages.error(request, "You don't have anything in cart")
                    return render(request, 'operations/cart.html', {'errors': errors})

                items = Items.objects.filter(cart=cart, product=product)[0]
                quantity = form.cleaned_data['quantity']
                quantity = int(quantity)

                if quantity <= product.quantity:
                    items.quantity = quantity
                    items.save()
                else:
                    messages.error(request, "You have reached the limit !!")

            else:
                product_id = str(product_id)
                quantity = form.cleaned_data['quantity']
                quantity = int(quantity)
                if quantity <= product.quantity:
                    request.session[settings.CART_SESSION_ID][product_id]['quantity'] = quantity
                    request.session.modified = True
                else:
                    messages.error("You have reached the limit !!")

            return redirect('operations:view_cart')

    return render(request, 'operations/cart.html',
                  {'form': form})


def delete_cart(request, product_id):
    try:
        product = Product.objects.get(id=product_id)
    except Product.DoesNotExist:

Xandar/orders/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, render_to_response
from core.models import OrderedItems, DeliveryAddresses, Customer, Wishlist
from django.views.generic import ListView

# Create your views here.


def show_ordered_items(request):

    if request.method == 'POST':
        pass
    else:
        #CHANGE
        orders = Wishlist.objects.filter(customer=request.user)
        delivery_addresses = DeliveryAddresses.objects.filter(customer=request.user)

        context = {
            'orders':orders,
            'addresses': delivery_addresses
        }
        return render(request, 'orders/checkout.html', context)


def apply_coupon(request):
    coupon = request.GET['coupon']
    total = int(request.GET['total'])
    if coupon == 'FIRST':
        discount = 0.10 * total
    else:
        discount  = 0
    total = total-discount
    return HttpResponse(total)


def place_order(request):
    UserAddress = DeliveryAddresses()
    context={}
    for key, values in request.GET.items():
            setattr(UserAddress, key, request.GET[key])
            context[key]=values
    UserAddress.customer = request.user
    UserAddress.save()
    #UPDATE MAKE CART
    orders = Wishlist.objects.filter(customer=request.user)
    context['orders']=orders
    return render(request, 'orders/order_confirmed.html', context)

class get_delivery_addresses(ListView):
    template_name = 'orders/delivery_address.html'

    def get_queryset(self):
        queryset = DeliveryAddresses.objects.filter(customer=self.request.user)
        return queryset

Xandar/operations/templates/operations/cart.html
{% extends 'base.html' %}
{% load static %}
{% load arith_tags %}
{% block content %}

    <body>


    <!-- Start Banner Area -->
    <section class="banner-area organic-breadcrumb">
        <div class="container">
            <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
                <div class="col-first">
                    <h1>Shopping Cart</h1>
                    <nav class="d-flex align-items-center">
                        <a href="index.html">Home<span class="lnr lnr-arrow-right"></span></a>
                        <a href="category.html">Cart</a>
                    </nav>
                </div>
            </div>
        </div>
    </section>
    <!-- End Banner Area -->

    <!--================Cart Area =================-->
    <section class="cart_area">
        <div class="container">
            <p class="cart_inner">

                {% if errors %}
                <div class="alert alert-info">
                <h4>{{errors}}</h4>
            </div>
                {% endif %}


            {% if messages %}
            {% for msg in messages %}
            <div class="alert alert-info">
                <h4>{{msg}}</h4>
            </div>
            {% endfor %}
            {% endif %}





                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            {% if not errors %}
                            <tr>
                                <th scope="col">Image</th>
                                <th scope="col">Product</th>
                                <th scope="col">Quantity</th>
                                <th scope="col">Remove</th>
                                <th scope="col">Unit Price</th>
                                <th scope="col">Price</th>
                            </tr>
                        {% endif %}

                        </thead>
                        <tbody>

                            {% for item in items %}


                            <tr>
                                <td>
                                    <div class="media">
                                        <div class="d-flex">
                                         <a href="#">
                                        <img src="{{item.product_img.image.url}}" width="80px"
                                        height="80px">
                                        </a>
                                        </div>
                                    </div>

                                </td>

                                <td>
                                    <div class="media">
                                    <div class="media-body">
                                            <p>{{item.product.name}}</p>
                                        </div>
                                    </div>
                                </td>

                                <td style="white-space:nowrap;">

                                    {{item.quantity}}
                                   <form action="{% url 'operations:update_cart' item.product.id %}" method="POST">
                                        {% csrf_token %}
                                        {{form.quantity}}
                                        <input type="submit" value="Update" class="btn btn-info">
                                    </form>
                                </td>
                                <td>
                                    <a href="{% url 'operations:delete_cart' item.product.id %}"><input type="submit" value="Remove" class="btn btn-info"></a>
                                </td>
                                <td>
                                    $ {{ item.unit_price}}
                                </td>
                                <td>
                                    $ {% multiply item.quantity item.unit_price %}
                                </td>
                            </tr>

                            {% endfor %}

                            {% if not errors %}
                            {% if not messages %}
                            <tr style="background-color: #5AC8FA ">
                                <td><b>Total </b></td>
                                <td colspan="4"></td>
                                <td colspan="num"><b>$ {{total_price }}</b></td>
                            </tr>
                            {% endif %}
                        {% endif %}
                        </tbody>
                    </table>
                    </div>

                     <p class="text-right">

                                    <div class="checkout_btn_inner d-flex align-items-center">
                                        <a class="gray_btn" href="{% url 'index' %}">Continue Shopping</a>

                                        {% if not errors %}
                                        {% if not messages %}
                                        <a class="primary-btn" href="checkout.html">Proceed to checkout</a>
                                        {% endif %}
                                        {% endif %}
                                    </div>

                    </p>

                </div>
            </div>
    </section>
    <!--================End Cart Area =================-->

    <script src="js/vendor/jquery-2.2.4.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
	 crossorigin="anonymous"></script>
	<script src="js/vendor/bootstrap.min.js"></script>
	<script src="js/jquery.ajaxchimp.min.js"></script>
	<script src="js/jquery.nice-select.min.js"></script>
	<script src="js/jquery.sticky.js"></script>
    <script src="js/nouislider.min.js"></script>
	<script src="js/jquery.magnific-popup.min.js"></script>
	<script src="js/owl.carousel.min.js"></script>
	<!--gmaps Js-->
	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE"></script>
	<script src="js/gmaps.min.js"></script>
	<script src="js/main.js"></script>
</body>



{% endblock %}

Xandar/operations/templates/operations/orders.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<body>

	<!-- Start Banner Area -->
	<section class="banner-area organic-breadcrumb">
		<div class="container">
			<div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
				<div class="col-first">
					<h1>Orders</h1>
					<nav class="d-flex align-items-center">
						<a href="index.html">Home<span class="lnr lnr-arrow-right"></span></a>
						<a href="#">Shop<span class="lnr lnr-arrow-right"></span></a>
						<a href="category.html">Fashon Category</a>
					</nav>
				</div>
			</div>
		</div>
	</section><br>
	<!-- End Banner Area -->

	<section class="cart-area">
	<div class="container" style="background-color:#f7f7f7;">
	<div class="row">
		<div class="col-lg-12">
			<div class="row">
				<div class="col-lg-4 col-sm-6" style="margin-bottom: 13px;">
					<div class="" style="text-align:center; padding: 13px 0px 0px 0px;">
						<a href="{% url 'products:product_detail' 1 %}">
							<img height="250px" width="250px" class="img-fluid" src="{% static 'img/product/p1.jpg' %}" alt="">
						</a>
					</div>
				</div>
				<div class="col-lg-4 col-sm-6">
					<div class="single-product" style="padding: 20px 0px 0px 0px;">
						<div class="product-details">
							<h3>Addidas New Hammer sole
								for Sports person</h3><hr color="#777777">
							<div class="price">
								<span>Price : </span>
								<span>$150.00</span>
							</div>
							<div class="price" style="position: absolute;">
								<h6>Description</h6>
								<div>Detailed Description</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-4 col-sm-6" style="padding: 20px 0px 0px 0px;">
						<div class="button-group-area mt-40" style="text-align:center">
							<a href="{% url 'operations:track' %}"><button type="button" class="btn btn-warning" style="margin-top:50px; width:70%;">Track Item</button></a><br><br>
							<a href="{% url 'products:product_detail' 1 %}">
								<button type="button" class="btn btn-info" style="width:70%;">Post Review</button></a>
								<br><br>
							<button type="button" class="btn btn-danger" style="width:70%;">Cancel Item</button><br>
						</div>
				</div>
			</div>
		</div>
	</div>
	</div><br>
	</section>


</body>


{% endblock %}

{% block scroll_js %}
<script type="text/javascript">
    $("html,body").scrollTop(320);
</script>
{% endblock scroll_js%}

Xandar/operations/templates/operations/wishlist.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <!-- Start Banner Area -->
    <section class="banner-area organic-breadcrumb">
        <div class="container">
            <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
                <div class="col-first">
                    <h1>Your Wishlist</h1>
                    <nav class="d-flex align-items-center">
                        <a href="{% url 'accounts:registration' %}">Home<span class="lnr lnr-arrow-right"></span></a>
                        <a href="#">Wishlist</a>
                    </nav>
                </div>
            </div>
        </div>
    </section>
    <!-- End Banner Area -->

<!--================Cart Area =================-->
    <section class="cart_area">
        <div class="container">
            <div class="cart_inner">
                <div class="table-responsive">
                    <table class="table">

                        {% if no_item_found %}
                        <div align="center">
                            <h3>No items found. Add something to cart.</h3><br><br>
                            <a class="primary-btn" href="{% url 'index' %}">Continue Shopping</a>
                        </div>
                        {% else %}
                        <form role="form" method="POST">
                            {% csrf_token %}
                        <thead>
                            <tr>
                                <th style="font-size:18px;" scope="col">PRODUCT</th>
                                <th style="font-size:18px;" scope="col">PRICE</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in items %}
                            <tr>
                                <td>
                                    <div class="media">
                                        <div class="d-flex">
                                            <a href= "{% url 'products:product_detail' item.product.id %}">
                                            <img src="{{ item.product_image.image.url }}" alt="Image Loading Soon..." height="100px" width="100px">
                                            </a>
                                        </div>
                                        <div class="media-body" style="color:black; font-size:15px;">
                                            <p>{{item.product.name}}</p>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <h5>₹ {{ item.product.price }}</h5>
                                </td>
                                <td>
                                        <button style="float:right;" type="button" class="btn btn-default" onclick="">Add to Cart</button>
                                </td>
<!--                                <td align="center">-->
<!--                                    <a href="#"><button style="float:right;" type="button" class="btn btn-success">View Details</button></a>-->
<!--                                </td>-->
                                <td>
                                     <button id="remove-btn" style="float:right;" type="button"
                                             onclick="abc({{item.id}})" class="btn btn-danger">Remove</button>
<!--                                    <a id="remove-btn" style="float:right;" type="submit"-->
<!--                                            href="{% url 'operations:delete_wishlist_items' item.id %}" class="btn btn-danger">Remove</a>-->
                                </td>
                            </tr>
                            {% endfor %}

                            <tr class="bottom_button">

                            </tr>
                            <tr class="out_button_area">
                                <td>

                                </td>
                                <td>

                                </td>
                                <td>

                                </td>

                                <td>
                                    <div style="float:right;" class="checkout_btn_inner d-flex align-items-center">
                                        <a class="gray_btn" href="{% url 'index' %}">Continue Shopping</a>
                                        <a class="primary-btn" href="#">Proceed to checkout</a>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                        {% endif %}
                        </form>
                    </table>
                </div>
            </div>
        </div>
    </section>
    <!--================End Cart Area =================-->
<script
src="https://code.jquery.com/jquery-1.12.4.js"
integrity="sha256-Qw82+bXyGq6MydymqBxNPYTaUXXq7c8v3CwiYwLLNXU="
crossorigin="anonymous"></script>


<script>

function abc(obj){

    var token = '{{ csrf_token }}'
     $.ajax({
                headers: {"X-CSRFToken": token},
                url: '/operations/delete-item/' + obj +'/',
                data: {'id':obj},
                type: 'POST',
                success: function(response) {
                    window.location.reload();
                    $(html).html(response);
                },
                error: function(error) {
                    console.log(error);
                }
            });
}

</script>



{% endblock content %}