Xandar/Xandar/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from Xandar import settings
from django.contrib.auth import views as auth_views
from accounts import views
from products.views import ProductListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('', include('core.urls')),
    path('product/', include('products.urls')),
    path('operations/', include('operations.urls')),
    path('product_list/', ProductListView.as_view(), name="product_list"),
    path('orders/', include('orders.urls')),



    

























    path('forgot_password/', views.check_email, name="check_email"),


    path('password-reset', 
    	auth_views.PasswordResetView.as_view(
            template_name='accounts/password_reset.html', html_email_template_name="accounts/email_reset_template.html",
            email_template_name='accounts/password_reset_email.html', subject_template_name="accounts/password_reset_subject.txt",
            ),
    		 name="password_reset"),

    path('password-reset/done', 
    	auth_views.PasswordResetDoneView.as_view(
    		template_name='accounts/password_reset_done.html'),
    		 name="password_reset_done"),

    path('password-reset-complete/', 
    	auth_views.PasswordResetCompleteView.as_view(
    		template_name='accounts/password_reset_complete.html'),
    		 name="password_reset_complete"),

    path('password-reset-confirm/<uidb64>/<token>/', 
    	auth_views.PasswordResetConfirmView.as_view(
    		template_name='accounts/password_reset_confirm.html'),
    		 name="password_reset_confirm"),


]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Xandar/accounts/urls.py
from django.urls import path, re_path
from . import views
app_name = 'accounts'
urlpatterns = [
    path('login/', views.login_page, name='login_app'),
    path('logout/', views.logout_user, name='logout_app'),
    path('reset_password/', views.reset_password, name="reset_password"),
    path('register/', views.user_register, name='registration'),
    path('dashboard/', views.dashboard, name='dashboard'),
    re_path('[A-Za-z0-9]*', views.login_page, name='login_app'),

]

Xandar/core/urls.py
from django.urls import path
from core import views
urlpatterns = [
    path('', views.index, name="index"),

]

Xandar/operations/urls.py
from django.urls import path
from . import views

app_name = 'operations'

urlpatterns = [
    path('wishlist/add/<int:pk>/', views.add_wishlist_item, name='add_wishlist_items'),
    path('wishlist/', views.list_wishlist_items, name='wishlist'),
    path('delete-item/<int:pk>/', views.delete_wishlist_items, name='delete_wishlist_items'),
    path('orders/', views.show_orders, name='orders'),
    path('address/', views.show_address, name='address'),
    path('track/', views.track_order, name='track'),
    path('cart/add/<int:product_id>/', views.add_to_cart, name='add_cart'),
    path('cart/', views.get_cart, name='view_cart'),
    path('cart/update/<int:product_id>/', views.update_cart, name='update_cart'),
    path('cart/delete/<int:product_id>/', views.delete_cart, name='delete_cart'),
]

Xandar/templates/partials/footer.html
	{% load static %}
	<!-- start footer Area -->
	<footer class="footer-area section_gap">
		<div class="container">
			<div class="row">
				<div class="col-lg-3  col-md-6 col-sm-6">
					<div class="single-footer-widget">
						<h6>About Us</h6>
						<p>
							Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore dolore
							magna aliqua.
						</p>
					</div>
				</div>
				<div class="col-lg-4  col-md-6 col-sm-6">
					<div class="single-footer-widget">
						<h6>Newsletter</h6>
						<p>Stay update with our latest</p>
						<div class="" id="mc_embed_signup">

							<form target="_blank" novalidate="true" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
							 method="get" class="form-inline">

								<div class="d-flex flex-row">

									<input class="form-control" name="EMAIL" placeholder="Enter Email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Email '"
									 required="" type="email">


									<button class="click-btn btn btn-default"><i class="fa fa-long-arrow-right" aria-hidden="true"></i></button>
									<div style="position: absolute; left: -5000px;">
										<input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
									</div>

									<!-- <div class="col-lg-4 col-md-4">
												<button class="bb-btn btn"><span class="lnr lnr-arrow-right"></span></button>
											</div>  -->
								</div>
								<div class="info"></div>
							</form>
						</div>
					</div>
				</div>
				<div class="col-lg-3  col-md-6 col-sm-6">
					<div class="single-footer-widget mail-chimp">
						<h6 class="mb-20">Instragram Feed</h6>
						<ul class="instafeed d-flex flex-wrap">
							<li><img src="{% static 'img/i1.jpg' %}" alt=""></li>
							<li><img src="{% static 'img/i2.jpg' %}" alt=""></li>
							<li><img src="{% static 'img/i3.jpg' %}" alt=""></li>
							<li><img src="{% static 'img/i4.jpg' %}" alt=""></li>
							<li><img src="{% static 'img/i5.jpg' %}" alt=""></li>
							<li><img src="{% static 'img/i6.jpg' %}" alt=""></li>
							<li><img src="{% static 'img/i7.jpg' %}" alt=""></li>
							<li><img src="{% static 'img/i8.jpg' %}" alt=""></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-2 col-md-6 col-sm-6">
					<div class="single-footer-widget">
						<h6>Follow Us</h6>
						<p>Let us be social</p>
						<div class="footer-social d-flex align-items-center">
							<a href="#"><i class="fa fa-facebook"></i></a>
							<a href="#"><i class="fa fa-twitter"></i></a>
							<a href="#"><i class="fa fa-dribbble"></i></a>
							<a href="#"><i class="fa fa-behance"></i></a>
						</div>
					</div>
				</div>
			</div>
			<div class="footer-bottom d-flex justify-content-center align-items-center flex-wrap">
				<p class="footer-text m-0"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="#" target="_blank">Django Boys</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
</p>
			</div>
		</div>
	</footer>

Xandar/templates/partials/navbar.html
<!-- Start Header Area -->
{% load static %}
	<header class="header_area sticky-header">
		<div class="main_menu">
			<nav class="navbar navbar-expand-lg navbar-light main_box">
				<div class="container">
					<!-- Brand and toggle get grouped for better mobile display -->
					<a class="navbar-brand logo_h" href="index.html"><img src="{% static 'img/logo.png' %}"></a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
					 aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<!-- Collect the nav links, forms, and other content for toggling -->
					<div class="collapse navbar-collapse offset" id="navbarSupportedContent">
						<ul class="nav navbar-nav menu_nav ml-auto">
							<li class="nav-item active"><a class="nav-link" href="{% url 'index' %}">Home</a></li>
							<li class="nav-item"><a class="nav-link" href="{% url 'product_list' %}">Shop Category</a></li>
							{% if user.is_authenticated %}

							<li class="nav-item submenu dropdown active">
								<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
								 aria-expanded="false">{{user.first_name }}</a>
								<ul class="dropdown-menu">
									<li class="nav-item"><a class="nav-link" href="{% url 'operations:wishlist'	 %}">Wishlist</a></li>
									<li class="nav-item"><a class="nav-link" href="{% url 'accounts:dashboard' %}">Dashboard</a></li>
									<li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout_app' %}">Logout</a></li>


								</ul>
							</li>
							{% else %}
							<li class="nav-item"><a class="nav-link" href="{% url 'accounts:login_app' %}">Login</a></li>
							<li class="nav-item"><a class="nav-link" href="{% url 'accounts:registration' %}">Register</a></li>
							{% endif %}

							<!-- <li class="nav-item"><a class="nav-link" href="contact.html">About Us</a></li> -->
						</ul>
						<ul class="nav navbar-nav navbar-right">
							<li class="nav-item"><a href="#" class="cart"><span class="ti-bag"></span></a></li>
							<li class="nav-item">
								<button class="search"><span class="lnr lnr-magnifier" id="search"></span></button>
							</li>
						</ul>
					</div>
				</div>
			</nav>
		</div>
		<div class="search_input" id="search_input_box">
			<div class="container">
				<form class="d-flex justify-content-between">
					<input type="text" class="form-control" id="search_input" placeholder="Search Here">
					<button type="submit" class="btn"></button>
					<span class="lnr lnr-cross" id="close_search" title="Close Search"></span>
				</form>
			</div>
		</div>
		<div id="notify-user"></div>
	</header>
	<!-- End Header Area -->