Xandar/Xandar/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from Xandar import settings
from django.contrib.auth import views as auth_views
from accounts import views
from products.views import ProductListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('', include('core.urls')),
    path('product/', include('products.urls')),
    path('operations/', include('operations.urls')),
    path('product_list/', ProductListView.as_view(), name="product_list"),
    path('orders/', include('orders.urls')),



    

























    path('forgot_password/', views.check_email, name="check_email"),


    path('password-reset', 
    	auth_views.PasswordResetView.as_view(
            template_name='accounts/password_reset.html', html_email_template_name="accounts/email_reset_template.html",
            email_template_name='accounts/password_reset_email.html', subject_template_name="accounts/password_reset_subject.txt",
            ),
    		 name="password_reset"),

    path('password-reset/done', 
    	auth_views.PasswordResetDoneView.as_view(
    		template_name='accounts/password_reset_done.html'),
    		 name="password_reset_done"),

    path('password-reset-complete/', 
    	auth_views.PasswordResetCompleteView.as_view(
    		template_name='accounts/password_reset_complete.html'),
    		 name="password_reset_complete"),

    path('password-reset-confirm/<uidb64>/<token>/', 
    	auth_views.PasswordResetConfirmView.as_view(
    		template_name='accounts/password_reset_confirm.html'),
    		 name="password_reset_confirm"),


]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Xandar/accounts/urls.py
from django.urls import path, re_path
from . import views
app_name = 'accounts'
urlpatterns = [
    path('login/', views.login_page, name='login_app'),
    path('logout/', views.logout_user, name='logout_app'),
    path('reset_password/', views.reset_password, name="reset_password"),
    path('register/', views.user_register, name='registration'),
    path('dashboard/', views.dashboard, name='dashboard'),
    re_path('[A-Za-z0-9]*', views.login_page, name='login_app'),

]

Xandar/core/urls.py
from django.urls import path
from core import views
urlpatterns = [
    path('', views.index, name="index"),

]

Xandar/operations/urls.py
from django.urls import path
from . import views

app_name = 'operations'

urlpatterns = [
    path('wishlist/add/<int:pk>/', views.add_wishlist_item, name='add_wishlist_items'),
    path('wishlist/', views.list_wishlist_items, name='wishlist'),
    path('delete-item/<int:pk>/', views.delete_wishlist_items, name='delete_wishlist_items'),
    path('orders/', views.show_orders, name='orders'),
    path('address/', views.show_address, name='address'),
    path('track/', views.track_order, name='track'),
    path('cart/add/<int:product_id>/', views.add_to_cart, name='add_cart'),
    path('cart/', views.get_cart, name='view_cart'),
    path('cart/update/<int:product_id>/', views.update_cart, name='update_cart'),
    path('cart/delete/<int:product_id>/', views.delete_cart, name='delete_cart'),
]

Xandar/accounts/models.py
from django.db import models

# Create your models here.

Xandar/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from core.models import Customer


class UserRegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Customer
        fields = ('first_name', 'last_name', 'email', 'password1', 'password2', 'gender', 'phone_number',)

Xandar/accounts/views.py
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import render, redirect
import random
from django.contrib import messages
from core.models import Customer
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.contrib.auth.decorators import login_required


def user_register(request):

    if not request.user.is_authenticated:
        if request.method == "POST":
            first_name = request.POST['first_name']
            last_name = request.POST['last_name']
            email = request.POST['email']
            password1 = request.POST['password1']
            password2 = request.POST['password2']
            gender = request.POST.get('gender')
            phone_number = request.POST['phone_number']

            if password1 == password2:
                if Customer.objects.filter(email=email).exists():
                    return render(request, 'accounts/register.html', context={'message': "Email already exists."})
                else:
                    username = first_name.replace(' ', '_').lower() + last_name + str(random.randint(1, 100))
                    while Customer.objects.filter(username=username).exists():
                        username = first_name.replace(' ', '_').lower() + last_name + str(random.randint(1, 100))
                    user = Customer.objects.create_user(username=username, first_name=first_name, last_name=last_name,
                                                        email=email, password=password1,
                                                        gender=gender, phone_number=phone_number)
                    user.save()

                    html_content = render_to_string('accounts/email_confirmation.html')

                    text_content = strip_tags(html_content)

                    msg = EmailMultiAlternatives('You are now registered', text_content,
                                                 'contact.realestate.information@gmail.com', [email])
                    msg.attach_alternative(html_content, "text/html")
                    msg.send()

                    return render(request, 'accounts/login.html',
                                  context={'message': "Registered Successfully. Now Log in"})
            else:
                return render(request, 'accounts/register.html', context={'message': "Passwords do not match"})
        return render(request, 'accounts/register.html')
    else:
        return redirect('index')


def dashboard(request):
    return render(request, 'accounts/dashboard.html')
















































#Aman
def login_page(request):
    if request.method == 'POST':
        email = request.POST.get('username')
        password = request.POST.get('password')
        try:
            current_customer = Customer.objects.get(email=email)
            user_authenticated = authenticate(request, username=current_customer.username, password=password)
            if user_authenticated is not None:
                login(request, user_authenticated)
                return redirect('index')
            else:
                context = {'message': 'Incorrect Password'}
        except Customer.DoesNotExist:
                context = {'message': 'No such user exist'}
        return render(request, 'accounts/login.html', context=context)
    else:
        if not request.user.is_authenticated:
            return render(request, 'accounts/login.html')
        else:
            return redirect('index')


def logout_user(request):
    logout(request)
    return redirect('accounts:login_app')










































































#Aayush
def check_email(request):
    if request.method == 'POST':
        mail = request.POST.get('email')
        user_email = Customer.objects.filter(email=mail)
        if user_email:
            request.session['user_email'] = mail
            return redirect('password_reset')
        else:
            messages.error(request, "Not a registered email")
            return redirect('check_email')
    else:
        return render(request, 'accounts/check_mail.html')


@login_required(login_url='/account/login')
def reset_password(request):
    if request.method == 'POST':
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        user = Customer.objects.get(username__exact=request.user.username)

        if password1==password2:
            if user.check_password(request.POST['old_password']):
                user.set_password(password1)
                user.save()
                return redirect('password_reset_complete')
            else:
                messages.error(request, "The old password you have entered is wrong")
                return render(request, 'accounts/reset_password.html')

        else:
            messages.error(request, "Password does not match")
            return render(request, 'accounts/reset_password.html')

    else:
        return render(request, 'accounts/reset_password.html')































































#Deepak

Xandar/accounts/templates/accounts/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<body>

    <!-- Start Banner Area -->
    <section class="banner-area organic-breadcrumb">
        <div class="container">
            <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
                <div class="col-first">
                    <h1>Dashboard</h1>
                    <nav class="d-flex align-items-center">
                        <a href="#">Home<span class="lnr lnr-arrow-right"></span></a>
                        <a href="{% url 'accounts:dashboard' %}">Dashboard</a>
                    </nav>
                </div>
            </div>
        </div>
    </section>
    <!-- End Banner Area -->

    <!--================Blog Categorie Area =================-->
    <section class="blog_categorie_area" style="padding-bottom: 5px;">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <div class="categories_post">
                        <img height="230px" width="100%" src="{% static 'img/dashboard/order.jpg' %}" alt="post">
                        <a href="{% url 'operations:orders' %}">
                            <div class="categories_details">
                                <div class="categories_text">
                                    <h5>Orders</h5>
                                    <div class="border_line"></div>
                                    <p>Dreams you achieved</p>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>

                <div class="col-lg-4">
                    <div class="categories_post">
                        <img height="230px" src="{% static 'img/dashboard/cart.jpg' %}" alt="post">
                        <a href="{% url 'operations:view_cart' %}">
                            <div class="categories_details">
                                <div class="categories_text">
                                        <h5>Cart</h5>
                                        <div class="border_line"></div>
                                        <p>Wheels of Happiness</p>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="categories_post">
                        <img height="230px" width="400px" src="{% static 'img/dashboard/wishlist.png' %}" alt="post">
                            <a href="{% url 'operations:wishlist' %}">
                                <div class="categories_details">
                                    <div class="categories_text">
                                            <h5>Wishlist</h5>
                                    <div class="border_line"></div>
                                    <p>Things soon to be yours</p>
                                </div>
                            </div>
                            </a>
                    </div>
                </div>


            </div>
        </div>
    </section>

    <!--================Blog Categorie Area =================-->
<section class="blog_categorie_area" style="padding-top: 0px;">
    <div class="container">
        <div class="row">
<div class="col-lg-4" align="right" style="margin-left: 190px;"><br>
                    <div class="categories_post">
                        <img height="230px" width="100%" src="{% static 'img/dashboard/security.jpg' %}" alt="post">
                        <a href="{% url 'accounts:reset_password' %}">
                            <div class="categories_details">
                                <div class="categories_text">
                                    <h5>Reset Password</h5>
                                    <div class="border_line"></div>
                                    <p>Your account, Our Responsibility</p>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>

                <div class="col-lg-4"><br>
                    <div class="categories_post">
                        <img height="230px" width="99%" src="{% static 'img/dashboard/address.png' %}" alt="post">
                        <a href="{% url 'operations:address' %}">
                            <div class="categories_details">
                                <div class="categories_text">
                                    <h5>Address</h5>
                                    <div class="border_line"></div>
                                    <p>Drop my orders here</p>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
    </div>
</section>
    <!-- End footer Area -->

</body>

{% endblock %}

{% block scroll_js %}
<script type="text/javascript">
    $("html,body").scrollTop(380);
</script>
{% endblock scroll_js%}

Xandar/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<body>
	<!-- Start Banner Area -->
	<section class="banner-area organic-breadcrumb">
		<div class="container">
			<div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
				<div class="col-first">
					<h1>Login/Register</h1>
					<nav class="d-flex align-items-center">
						<a href="index.html">Home<span class="lnr lnr-arrow-right"></span></a>
						<a href="category.html">Login/Register</a>
					</nav>
				</div>
			</div>
		</div>
	</section>
	<!-- End Banner Area -->

	<!--================Login Box Area =================-->
	<section class="login_box_area section_gap">
		<div class="container">
			<div class="row">
				<div class="col-lg-6">
					<div class="login_box_img">
						<img class="img-fluid" src="{% static 'img/login.jpg' %}" alt="">
						<div class="hover">
							<h4>New to our website?</h4>
							<p>There are advances being made in science and technology everyday, and a good example of this is the</p>
							<a class="primary-btn" href="{% url 'accounts:registration' %}">Create an Account</a>
						</div>
					</div>
				</div>
				<div class="col-lg-6">

					<div class="login_form_inner">
						<h3>Log in to enter</h3>
						<div class="form-group" style="color:red;">{% if message %}
								{{message}}
							{% endif %}
						</div>
						<form class="row login_form" method="post" id="contactForm">
							{% csrf_token %}
							<div class="col-md-12 form-group">
								<input type="text" class="form-control" name="username" placeholder="Email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Email'">
							</div>
							<div class="col-md-12 form-group">
								<input type="password" class="form-control" name="password" placeholder="Password" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Password'">
							</div>
							<div class="col-md-12 form-group">
								<button type="submit" value="submit" class="primary-btn" id="submitbutton">Log In</button>
								<a href="{% url 'check_email' %}">Forgot Password?</a>
							</div>
						</form>
					</div>

				</div>
			</div>
		</div>
	</section>
	<!--================End Login Box Area =================-->
</body>
{% endblock %}
{% block scroll_js %}
<script type="text/javascript">
    $("html,body").scrollTop(400);
</script>
{% endblock scroll_js%}

Xandar/accounts/templates/accounts/messages.html
{% if messages %}
    {% for message in messages %}
        <div id="message" class="container">
            <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
                <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span></button>
                <strong>
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                        Error:
                    {% else %}
                        {{ message.tags|title }}
                    {% endif %}
                </strong>
                {{message}}

            </div>
        </div>
    {% endfor %}
{% endif %}

Xandar/accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
   <style>
      /* The message box is shown when the user clicks on the password field */
      #message {
        display:none;
        background: #f7f7f7;
        color: #000;
        position: relative;
        padding: 10px 0px 1px 10px;
        margin-top: 10px;
      }

      #message p {
         margin : 8px;
         padding: 0px 0px 0px 35px;
         font-size: 14px;
      }

      /* Add a green text color and a checkmark when the requirements are right */
      .valid {
        color: green;
      }

      .valid:before {
        position: relative;
        left: -35px;
        content: "✔";
      }

      /* Add a red text color and an "x" when the requirements are wrong */
      .invalid {
        color: red;
      }

      .invalid:before {
        position: relative;
        left: -35px;
        content: "✖";
      }
   </style>

   <style>
      .alert {
        padding: 20px;
        background-color: #f44336;
        color: white;
        transition: opacity 0.6s;
      }

      .closebtn {
        margin-left: 15px;
        color: white;
        font-weight: bold;
        float: right;
        font-size: 22px;
        line-height: 20px;
        cursor: pointer;
        transition: 0.3s;
      }

      .closebtn:hover {
        color: black;
      }
   </style>

   <!-- Start Banner Area -->
   <section class="banner-area organic-breadcrumb">
      <div class="container">
         <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
            <div class="col-first">
               <h1>Register New User</h1>
               <nav class="d-flex align-items-center">
                  <a href="">Home<span class="lnr lnr-arrow-right"></span></a>
                  <a href="{% url 'accounts:registration' %}">Register New User</a>
               </nav>
            </div>
         </div>
      </div>
   </section>
   <!-- End Banner Area -->

   <!--================Login Box Area =================-->
   <section class="login_box_area section_gap">
      <center>
         <div class="col-lg-6">
               <div class="login_form_inner" style="margin-top:0px">
                  <h2>Registration Form</h2><br>
                  {% if message %}
                  <div class="alert">
                    <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
                        {{message}}
                  </div>
                  {% endif %}

                  <form class="row login_form" method="POST" id="contactForm">
                     {% csrf_token %}
                     <span class="col-md-12 form-group" style="color:red;">* Fields are mandatory</span>
                     <div class="col-md-12 form-group">
                        <input type="text" class="form-control is-valid" id="fn" name="first_name"
                              placeholder="First Name *" onfocus="this.placeholder = 'First Name *'"
                              data-validation-help="Do not add numbers or special characters"
                              onblur="this.placeholder = 'First Name'" pattern="^[a-zA-Z\s]+$"
                              maxlength="30" required>
                     </div>
                     <div class="col-md-12 form-group">
                        <input type="text" class="form-control is-valid" id="ln" name="last_name"
                              placeholder="Last Name" onfocus="this.placeholder = 'Last Name'"
                              data-validation-help="Do not add numbers or special characters"
                              onblur="this.placeholder = 'Last Name'" pattern="^[a-zA-Z\s]+$"
                              maxlength="20">
                     </div>
                     <div class="col-md-12 form-group">
                        <input type="email" class="form-control is-valid" id="name" name="email"
                              placeholder="E-mail *" onfocus="this.placeholder = 'E-mail *'"
                              onblur="this.placeholder = 'E-mail'" maxlength="50" required
                              data-validation="email" data-validation-error-msg="Enter a valid e-mail. Eg: abc@gmail.com">
                     </div>
                     <div class="col-md-12 form-group">
                        <input type="Password" class="form-control is-valid" id="txtPassword" name="password1"
                              placeholder="Password *" onfocus="this.placeholder = 'Password *'"
                              onblur="this.placeholder = 'Password *'" pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}"
                              maxlength="15" required>
                        <div id="message" align="left">
                           <h5>Password must contain the following:</h5>
                           <p id="letter" class="invalid">A lowercase letter</p>
                           <p id="capital" class="invalid">A capital (uppercase) letter</p>
                           <p id="number" class="invalid">A number</p>
                           <p id="length" class="invalid">Minimum 8 characters</p>
                        </div>
                     </div>
                     <div class="col-md-12 form-group">
                        <input type="Password" class="form-control is-valid" id="txtConfirmPassword"
                              name="password2" placeholder="Confirm Password *" onfocus="this.placeholder = 'Confirm Password *'"
                              data-validation="confirmation" pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}"
                              onblur="this.placeholder = 'Confirm Password *'" maxlength="15" required>
                     </div>
                     <div class="col-md-12 is-valid" align="left">
                        <br><input type="radio" name="gender" value="True" checked> Male
                        <input style="margin-left:150px;" type="radio" name="gender" value="False"> Female<br><br>
                     </div>
                     <div class="col-md-12 form-group">
                        <input type="text" class="form-control is-valid" id="name" name="phone_number"
                              placeholder="Phone Number *" onfocus="this.placeholder = 'Phone Number *'"
                              onblur="this.placeholder = 'Phone Number'" pattern="[789][0-9]{9}"
                              data-validation-help="Number must be in Indian format +91-(AAAAA BBBBB)"
                              maxlength="10" required>
                     </div>
                     <div class="col-md-12 form-group is-valid">
                        <button type="submit" id="btnSubmit" value="submit"
                              class="primary-btn">Register</button>
                     </div>
                  </form>
                  <div>
                     Already A User?? <a href="{% url 'accounts:login_app' %}">Sign In</a>
                  </div><br>
               </div>
            </div>
      </center>

   </section>
   <!--================End Login Box Area =================-->


   <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
   <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.3.26/jquery.form-validator.min.js"></script>

   <script>
      $.validate();
      $('#my-textarea').restrictLength( $('#max-length-element') );
   </script>
   <script>
      var myInput = document.getElementById("txtPassword");
      var letter = document.getElementById("letter");
      var capital = document.getElementById("capital");
      var number = document.getElementById("number");
      var length = document.getElementById("length");

      // When the user clicks on the password field, show the message box
      myInput.onfocus = function() {
        document.getElementById("message").style.display = "block";
      }

      // When the user clicks outside of the password field, hide the message box
      myInput.onblur = function() {
        document.getElementById("message").style.display = "none";
      }

      // When the user starts to type something inside the password field
      myInput.onkeyup = function() {
        // Validate lowercase letters
        var lowerCaseLetters = /[a-z]/g;
        if(myInput.value.match(lowerCaseLetters)) {
         letter.classList.remove("invalid");
         letter.classList.add("valid");
        } else {
         letter.classList.remove("valid");
         letter.classList.add("invalid");
        }

        // Validate capital letters
        var upperCaseLetters = /[A-Z]/g;
        if(myInput.value.match(upperCaseLetters)) {
         capital.classList.remove("invalid");
         capital.classList.add("valid");
        } else {
         capital.classList.remove("valid");
         capital.classList.add("invalid");
        }

        // Validate numbers
        var numbers = /[0-9]/g;
        if(myInput.value.match(numbers)) {
         number.classList.remove("invalid");
         number.classList.add("valid");
        } else {
         number.classList.remove("valid");
         number.classList.add("invalid");
        }

        // Validate length
        if(myInput.value.length >= 8) {
         length.classList.remove("invalid");
         length.classList.add("valid");
        } else {
         length.classList.remove("valid");
         length.classList.add("invalid");
        }
      }
   </script>

{% endblock %}
{% block scroll_js %}
<script type="text/javascript">
    $("html,body").scrollTop(400);
</script>
{% endblock scroll_js%}

Xandar/accounts/templates/accounts/reset_password.html
{% extends 'base.html' %}
 {% block content %}
<style>
   /* The message box is shown when the user clicks on the password field */
   #messages {
     display:none;
     background: #f7f7f7;
     color: #000;
     position: relative;
     padding: 20px;
     margin-top: 10px;
   }

   #messages p {
      padding: 10px 35px;
      font-size: 15px;
   }

   /* Add a green text color and a checkmark when the requirements are right */
   .valid {
     color: green;
   }

   .valid:before {
     position: relative;
     left: -35px;
     content: "✔";
   }

   /* Add a red text color and an "x" when the requirements are wrong */
   .invalid {
     color: red;
   }

   .invalid:before {
     position: relative;
     left: -35px;
     content: "✖";
   }
</style>

 <!-- Start Banner Area -->
   <section class="banner-area organic-breadcrumb">
      <div class="container">
         <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
            <div class="col-first">
               <h1>Reset Password</h1>
               <nav class="d-flex align-items-center">
                  <a href="{% url 'index' %}">Home<span class="lnr lnr-arrow-right"></span></a>
                  <a href="{% url 'accounts:reset_password' %}">Reset Password</a>
               </nav>
            </div>
         </div>
      </div>
   </section>
   <!-- End Banner Area -->



<section class="login_box_area section_gap">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-sm-12">
                    <div class="login_form_inner">
                    	<p class="text-center"> <strong>Use the form below to change your password. <br> Your password cannot be the same as your username.</strong></p>
  {% include 'accounts/messages.html' %}

<form method="POST" action="{% url 'accounts:reset_password' %}" style="margin: 0 auto; width:250px;">
	
	{% csrf_token %}
	<div class="form-group">
	<label for="old_password">Old Password</label>
	<input type="password" class="form-control" name="old_password">
<br>	
	<label for="new_password">New Password</label>
	<input type="password" id="txtPassword" pattern="(?=^.{8,}$)((?=.*\d)|(?=.*\W+))(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$" class="form-control" name="password1" required>


<div id="messages" align="left">
   <h5>Password must contain the following:</h5><br>
   <p id="letter" class="invalid">A lowercase letter</p>
   <p id="capital" class="invalid">A capital (uppercase) letter</p>
   <p id="number" class="invalid">A number</p>
   <p id="length" class="invalid">Minimum 8 characters</p>
</div>


<br>
	<label for="new_password">Comfirm Password</label>
	<input type="password" class="form-control" name="password2">
<br>
	<button class="btn btn-primary" type="submit">Change Password</button>

</form>
</div>
</div>
</div>
</div>
</div>
</section>




<script>
   var myInput = document.getElementById("txtPassword");
   var letter = document.getElementById("letter");
   var capital = document.getElementById("capital");
   var number = document.getElementById("number");
   var length = document.getElementById("length");

   // When the user clicks on the password field, show the message box
   myInput.onfocus = function() {
     document.getElementById("messages").style.display = "block";
   }

   // When the user clicks outside of the password field, hide the message box
   myInput.onblur = function() {
     document.getElementById("messages").style.display = "none";
   }

   // When the user starts to type something inside the password field
   myInput.onkeyup = function() {
     // Validate lowercase letters
     var lowerCaseLetters = /[a-z]/g;
     if(myInput.value.match(lowerCaseLetters)) {
      letter.classList.remove("invalid");
      letter.classList.add("valid");
     } else {
      letter.classList.remove("valid");
      letter.classList.add("invalid");
     }

     // Validate capital letters
     var upperCaseLetters = /[A-Z]/g;
     if(myInput.value.match(upperCaseLetters)) {
      capital.classList.remove("invalid");
      capital.classList.add("valid");
     } else {
      capital.classList.remove("valid");
      capital.classList.add("invalid");
     }

     // Validate numbers
     var numbers = /[0-9]/g;
     if(myInput.value.match(numbers)) {
      number.classList.remove("invalid");
      number.classList.add("valid");
     } else {
      number.classList.remove("valid");
      number.classList.add("invalid");
     }

     // Validate length
     if(myInput.value.length >= 8) {
      length.classList.remove("invalid");
      length.classList.add("valid");
     } else {
      length.classList.remove("valid");
      length.classList.add("invalid");
     }
   }
</script>
{% endblock content %}



{% block scroll_js %}
<script type="text/javascript">
$("html,body").scrollTop(450);
</script>
{% endblock scroll_js%}